### PR TITLE
Rest: Handle IPv6 link local addresses with zone identifier in Authenticate

### LINKED ISSUE #268: Cannot start a cluster on IPv6 link local scoped addresses
This affects microcluster `v2` and `v3`. 
Trying to start a cluster on IPv6 link local scoped addresses is not working as expected and does not report any errors either.

See this reproducer using the example package. Use any of your link local addresses and modify the scope (interface):

```bash
#!/bin/bash

rm -rf /tmp/m*

microd --state-dir /tmp/m1 &
microctl --state-dir /tmp/m1 waitready
microd --state-dir /tmp/m2 &
microctl --state-dir /tmp/m2 waitready
microd --state-dir /tmp/m3 &
microctl --state-dir /tmp/m3 waitready

microctl --state-dir /tmp/m1 init m1 [fe80::173d:4cbe:eb86:c0a9%wlp0s20f3]:9001 --bootstrap

# Fake custom cert
cp /tmp/m1/cluster.crt /tmp/m1/certificates/foo.crt
cp /tmp/m1/cluster.key /tmp/m1/certificates/foo.key
cp /tmp/m1/cluster.crt /tmp/m1/certificates/foo2.crt
cp /tmp/m1/cluster.key /tmp/m1/certificates/foo2.key


# Join additional members
token=$(microctl --state-dir /tmp/m1 tokens add m2)
microctl --state-dir /tmp/m2 init m2 [fe80::173d:4cbe:eb86:c0a9%wlp0s20f3]:9002 --token "$token"
token=$(microctl --state-dir /tmp/m1 tokens add m3)
microctl --state-dir /tmp/m3 init m3 [fe80::173d:4cbe:eb86:c0a9%wlp0s20f3]:9003 --token "$token"

microctl --state-dir /tmp/m1 cluster list

```

### PR DESCRIPTION
**Pull request by rapour**
This PR suggests a fix for #268 

Closes https://github.com/canonical/microcluster/issues/268

### CODE REVIEW

File: internal/db/dqlite.go [hunk 1]
```diff
@@ -397,7 +398,7 @@ func dqliteNetworkDial(ctx context.Context, addr string, db *DqliteDB) (net.Conn
 		Host:       addr,
 	}
 
-	path := fmt.Sprintf("https://%s/%s/%s", addr, internalTypes.InternalEndpoint, "database")
+	path := fmt.Sprintf("https://%s/%s/%s", strings.Replace(addr, "%", "%25", 1), internalTypes.InternalEndpoint, "database")
```
Comment (roosterfish) [inline internal/db/dqlite.go]: The `url.Parse` (and the internal [`parse`](https://github.com/golang/go/blob/master/src/net/url/url.go)) do have some logic checks for this but as you have mentioned they expect the zone identifier to be already encoded (check for `%25`).
So I wonder if we can circumvent this by crafting the `request.URL` in a different way. Meaning that we provide the host and URL separately. Maybe the `url` package already has some tooling that could be useful for this?

File: rest/types/addrport.go [hunk 2]
```diff
@@ -94,6 +94,19 @@ func (a AddrPort) String() string {
 	return a.AddrPort.String()
 }
 
+// WithoutZone returns the AddrPort with the zone identifier removed from the address. It will return the same
+// AddrPort as the receiver if the address is ipv4 or ipv6 without zone identifier.
+func (a AddrPort) WithoutZone() AddrPort {
```
Comment (roosterfish) [inline rest/types/addrport.go]: It bugs me a little bit that there is nothing in the standard library for such checks so we have to remove the zone ID suffix ourselves for this check.

I think it's ok that we store the IPv6 with zone ID internally as this is what was ultimately configured so it's getting passed down in `hostAddress`. 
Have you checked if the `x/net/ipv6` package has something useful we can use to deal with the zone ID in the address?

**Review by roosterfish — COMMENTED** [review]
Hi, thanks for your investigation on this. Please see my comments below.

**Comment by roosterfish** [comment]
Can you please rebase from `v3`. We have added some more linter rules.

File: internal/db/dqlite.go (hunk 1 above)
Comment (rapour) [reply internal/db/dqlite.go]: I couldn't find anything useful from the `url` package as it probably doesn't recognize the textual representation of ipv6 in RFC4007:
https://github.com/golang/go/blob/b07b20fbb591ac77158e1089299ce5acad71ffde/src/net/url/url_test.go#L704-L709
If you had any other directions in mind I would be happy to investigate. However, we can think of an alternative too. My impression is that `addr` string here is of type `AddrPort`, since `NewCluster` parses the input address into `AddrPort`. If it is indeed the case, we could first  parse the `addr` string into `AddrPort` and then handle these subtleties there in a canonical manner.

File: rest/types/addrport.go (hunk 2 above)
Comment (rapour) [reply rest/types/addrport.go]: The approach here is to strip the zone ID so it can be compared to the host and it uses the following feature from the standard library: 

https://github.com/golang/go/blob/b07b20fbb591ac77158e1089299ce5acad71ffde/src/net/netip/netip.go#L701-L704

Although the check is manual, the way to strip the zone ID is something done via the standard library. Interestingly, I found another way to strip the zone ID by using `WithZone("")`:
https://github.com/golang/go/blob/b07b20fbb591ac77158e1089299ce5acad71ffde/src/net/netip/netip.go#L489-L492
We can move to this one but at the end, both do the same and strip the zone ID so it becomes comparable to `Host`. The `netip` package has some comparison methods but I suspect any other solution would be as mediocre as this one since http request's `r.Host` is a string and will need parsing before any other checks. The `RemoteAddr` of the http request also has the full `host%zone` info which is comparable to the original `hostAddress` but there are no guarantees about the format of it and I'm not sure whether it's a good idea to replace it with the `r.Host`. 

As a side note, please also [see this](https://github.com/golang/go/issues/71362).

Comment (roosterfish) [reply rest/types/addrport.go]: I like the idea of using the standard libraries `WithZone("")` using an empty string. Let's do this.

File: internal/db/dqlite.go (hunk 1 above)
Comment (roosterfish) [reply internal/db/dqlite.go]: Is it your idea to modify the `AddrPort` type's `String()` to include the encoding? That sounds reasonable and also makes it usable for future use cases.

File: rest/types/addrport.go (hunk 2 above)
Comment (rapour) [reply rest/types/addrport.go]: Done, now we have the same interface for `types.AddrPort` as there is for `netip.Addr` when it comes to zone ID modifications.

File: internal/db/dqlite.go (hunk 1 above)
Comment (rapour) [reply internal/db/dqlite.go]: I'm afraid changing the `String()` encoding may break other parts of the code that expect non-encoded `host%zone`. How do you feel about something like this: 
```
func dqliteNetworkDial(ctx context.Context, addr string, db *DqliteDB) (net.Conn, error) {
	addrPort, err := types.ParseAddrPort(addr)
	if err != nil {
		return nil, fmt.Errorf("Failed to parse the address: %w", err)
	}
	....
	request.URL = &url.URL{
		Scheme: "https",
		Host:   addrPort.String(),
		Path:   fmt.Sprintf("/%s/%s", internalTypes.InternalEndpoint, "database"),
	}
	...
}
```
This way we can actually circumvent the `url.Parse` and still keep the address validation.

Comment (roosterfish) [reply internal/db/dqlite.go]: That's exactly what I meant in my original comment:

> So I wonder if we can circumvent this by crafting the request.URL in a different way. Meaning that we provide the host and URL separately.

So if I understood your comment right, we don't have to apply any special encoding when doing `Host: addrPort.String()`? That seems much preferable.

File: rest/types/addrport.go (hunk 2 above)
Comment (roosterfish) [reply rest/types/addrport.go]: Can we use the `WithZone("")` from the std lib? I thought we use this one instead of having our own `WithoutZone()`.

File: rest/types/addrport_test.go [hunk 3]
```diff
@@ -8,7 +8,6 @@ import (
 )
 
 func TestAddrPortWithoutZone(t *testing.T) {
-
```
Comment (roosterfish) [inline rest/types/addrport_test.go]: We don't squash the commits when merging. Can you please squash this commit with the one where you have introduced the test?
This way you don't have a commit in the PR which adds lines which are being removed again by one of the follow up commits.

**Comment by roosterfish** [comment]
Ah sorry. I haven't seen that you have already all the changes in the last commits.
Please see my other comment regarding squashing.

File: rest/types/addrport.go (hunk 2 above)
Comment (roosterfish) [reply rest/types/addrport.go]: Saw the latest commits too late. Fixed.

File: rest/types/addrport_test.go (hunk 3 above)
Comment (roosterfish) [reply rest/types/addrport_test.go]: This also applies to the other latest changes regarding `WithZone("")`.

File: internal/db/dqlite.go (hunk 1 above)
Comment (rapour) [reply internal/db/dqlite.go]: Yes Exactly

File: rest/types/addrport_test.go (hunk 3 above)
Comment (rapour) [reply rest/types/addrport_test.go]: Done

**Review by roosterfish — DISMISSED** [review]
Thanks for this!

**Comment by roosterfish** [comment]
@rapour I cannot merge before your commits aren't signed as this is a rule of the repo.

**Review by roosterfish — APPROVED** [review]
LGTM!
